const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
const FETCH_CLIENTS_REQUESTED = 'FETCH_CLIENTS_REQUESTED';
const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

export { FETCH_CLIENTS_SUCCESS, FETCH_CLIENTS_REQUESTED, FETCH_CLIENTS_FAILURE }