const CLIENT_FORM_OPEN = 'CLIENT_FORM_OPEN';
const CLIENT_FORM_CHANGE = 'CLIENT_FORM_CHANGE';
const CLIENT_FORM_CLOSE = 'CLIENT_FORM_CLOSE';

export { CLIENT_FORM_OPEN, CLIENT_FORM_CHANGE, CLIENT_FORM_CLOSE }